export interface CloudflareStreamClientOptions {
  accountId: string
  apiToken: string
}

export interface LiveInput {
  uid: string
  rtmps: { url: string; streamKey: string }
  srt: { url: string; streamId: string }
  webRTC: { url: string }
  created: string
}

export interface VideoItem {
  uid: string
  status: { state: string; pctComplete?: number; errorReasonCode?: string; errorReasonText?: string }
  meta: Record<string, string>
  created: string
  modified: string
  size: number
  preview: string
  readyToStream: boolean
  thumbnail: string
  playback: { hls: string; dash: string }
  duration: number
  input: { width: number; height: number }
  liveInput?: string
  clippedFrom?: string
  watermark?: string
  publicDetails?: { title: string; share_link?: string }
  requireSignedURLs: boolean
  allowedOrigins: string[]
  maxDurationSeconds?: number
  uploadURL?: string
}

export class CloudflareStreamClient {
  private accountId: string
  private apiToken: string
  private baseUrl: string

  constructor(env: { CF_ACCOUNT_ID?: string; CF_STREAM_API_TOKEN?: string }) {
    if (!env.CF_ACCOUNT_ID || !env.CF_STREAM_API_TOKEN) {
      throw new Error('Cloudflare Stream credentials not configured')
    }
    this.accountId = env.CF_ACCOUNT_ID
    this.apiToken = env.CF_STREAM_API_TOKEN
    this.baseUrl = `https://api.cloudflare.com/client/v4/accounts/${this.accountId}/stream`
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const res = await fetch(`${this.baseUrl}${path}`, {
      ...init,
      headers: {
        Authorization: `Bearer ${this.apiToken}`,
        'Content-Type': 'application/json',
        ...init?.headers,
      },
    })
    if (!res.ok) {
      const err = await res.text()
      throw new Error(`Cloudflare Stream API error: ${res.status} ${err}`)
    }
    const json = await res.json() as { success: boolean; result: T; errors: Array<{ message: string }> }
    if (!json.success) {
      throw new Error(`Cloudflare Stream API error: ${json.errors?.[0]?.message || 'Unknown'}`)
    }
    return json.result
  }

  async createLiveInput(name: string, meta?: Record<string, string>): Promise<LiveInput> {
    return this.request<LiveInput>('/live_inputs', {
      method: 'POST',
      body: JSON.stringify({
        meta: { name, ...meta },
        recording: { mode: 'automatic', timeoutSeconds: 10, requireSignedURLs: false },
      }),
    })
  }

  async listLiveInputs(): Promise<LiveInput[]> {
    const result = await this.request<{ liveInputs: LiveInput[] }>('/live_inputs')
    return result.liveInputs || []
  }

  async deleteLiveInput(uid: string): Promise<void> {
    await this.request<void>(`/live_inputs/${uid}`, { method: 'DELETE' })
  }

  async listVideos(): Promise<VideoItem[]> {
    const result = await this.request<{ videos: VideoItem[] }>('/?limit=100')
    return result.videos || []
  }

  async getVideo(uid: string): Promise<VideoItem> {
    return this.request<VideoItem>(`/${uid}`)
  }

  async deleteVideo(uid: string): Promise<void> {
    await this.request<void>(`/${uid}`, { method: 'DELETE' })
  }

  /**
   * Returns playback URLs. When a Stream binding is supplied, the token is
   * generated by Cloudflare rather than by signing with an API token.
   */
  async getPlaybackUrl(
    uid: string,
    streamBinding?: Stream,
    options: { requireToken?: boolean } = {}
  ): Promise<{ hls: string; dash: string; thumbnail: string; token?: string }> {
    const video = await this.getVideo(uid)

    if (!options.requireToken) {
      return { hls: video.playback.hls, dash: video.playback.dash, thumbnail: video.thumbnail }
    }

    if (!streamBinding) {
      throw new Error('Cloudflare Stream binding is required for signed playback')
    }

    const token = await streamBinding.video(uid).generateToken()
    return {
      hls: replaceStreamAssetId(video.playback.hls, token),
      dash: replaceStreamAssetId(video.playback.dash, token),
      thumbnail: replaceStreamAssetId(video.thumbnail, token),
      token,
    }
  }

  async getStreamHealth(uid: string): Promise<{
    status: string
    live: boolean
    connected: boolean
    frameRate?: number
    width?: number
    height?: number
  }> {
    try {
      const video = await this.getVideo(uid)
      return {
        status: video.status.state,
        live: video.status.state === 'live-inprogress',
        connected: video.status.state !== 'error',
        ...(video.input || {}),
      }
    } catch {
      return { status: 'unknown', live: false, connected: false }
    }
  }

  async getVideoViews(uid: string, start?: string, end?: string): Promise<{
    totalViews: number
    timeSeries: Array<{ datetime: string; views: number }>
  }> {
    const params = new URLSearchParams()
    if (start) params.append('start', start)
    if (end) params.append('end', end)
    const query = params.toString() ? `?${params.toString()}` : ''
    return this.request(`/analytics/views${query}`)
  }
}

/** Replace only the Stream asset ID path segment; preserve manifest/query path. */
function replaceStreamAssetId(assetUrl: string, token: string): string {
  const url = new URL(assetUrl)
  const parts = url.pathname.split('/')
  const idIndex = parts.findIndex((part) => part.length > 0)
  if (idIndex < 0) throw new Error('Invalid Cloudflare Stream playback URL')
  parts[idIndex] = token
  url.pathname = parts.join('/')
  return url.toString()
}
